# Generated by Django 3.1.7 on 2021-12-03 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('task', models.BooleanField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='additional_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
