# Generated by Django 3.1.7 on 2022-02-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icalendar', '0002_event_taskcompleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('color', models.CharField(choices=[('BL', 3367679), ('GR', 2024494), ('RE', 14951966), ('PI', 14950057), ('YE', 15394335), ('PU', 12656356), ('OR', 16493079)], default='BL', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(related_name='event', to='icalendar.Tag'),
        ),
    ]
