# Generated by Django 3.1.7 on 2022-04-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icalendar', '0005_auto_20220313_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
