# Generated by Django 3.1.7 on 2022-04-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icalendar', '0006_auto_20220403_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.CharField(choices=[('HI', 'High'), ('ME', 'Medium'), ('LO', 'Low')], default='ME', max_length=2),
        ),
    ]
