# Generated by Django 3.1.7 on 2022-03-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icalendar', '0007_auto_20220319_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='urgency',
            field=models.CharField(choices=[('CR', 'Critical'), ('HI', 'High'), ('ME', 'Medium'), ('LO', 'Low')], max_length=2),
        ),
    ]
